[package]
name = "web_hello"
version = "0.1.0"
authors = ["Atsushi Kikuchi <nzlhl1d19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"